# Generated by Django 4.0.6 on 2023-04-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_custom_disc_1_user_custom_disc_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_disc_1_name',
            field=models.CharField(default='Descuento 1', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_disc_2_name',
            field=models.CharField(default='Descuento 2', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_disc_3_name',
            field=models.CharField(default='Descuento 3', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_disc_4_name',
            field=models.CharField(default='Descuento 5', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_disc_5_name',
            field=models.CharField(default='Descuento 5', max_length=250),
        ),
    ]
