# Generated by Django 4.0.6 on 2023-12-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_logbook_incentive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oaci_id', models.CharField(max_length=250)),
                ('iata_id', models.CharField(max_length=250)),
                ('airport_name', models.CharField(max_length=250)),
            ],
        ),
    ]
